-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 14:17:17 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema overlandoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema overlandoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `overlandoo` DEFAULT CHARACTER SET utf8 ;
USE `overlandoo` ;

-- -----------------------------------------------------
-- Table `overlandoo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `overlandoo`.`user` (
  `userID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `countriesTravelled` SMALLINT(6) NULL,
  `email` MEDIUMBLOB NOT NULL,
  `avatar` VARCHAR(45) NOT NULL DEFAULT 'defaultAvatar.jpg',
  `age` TINYINT(4) NULL,
  `gender` TINYINT(4) NULL,
  `status` VARCHAR(45) NULL,
  `lastOnline` DATETIME NULL,
  `durationOnline` VARCHAR(45) NULL,
  `currentlyAt` VARCHAR(45) NULL,
  `subPlan` VARCHAR(45) NULL,
  `subDuration` VARCHAR(45) NULL,
  `subDate` DATE NULL,
  `joinDate` TIMESTAMP NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `overlandoo`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `overlandoo`.`route` (
  `routeID` BIGINT(20) NOT NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `fromLocation` VARCHAR(45) NULL,
  `toLocation` VARCHAR(45) NULL,
  `fromStationLocation` VARCHAR(45) NULL,
  `toStationLocation` VARCHAR(45) NULL,
  `duration` TIME NULL,
  `frequency` VARCHAR(45) NULL,
  `fare` DECIMAL(10,0) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `lastUpdated` TIMESTAMP NULL,
  `votes` INT(11) NULL,
  PRIMARY KEY (`routeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `overlandoo`.`userToRoute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `overlandoo`.`userToRoute` (
  `userToRouteID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userID` INT NULL,
  `routeID` INT NULL,
  INDEX `idroute_idx` (`routeID` ASC),
  INDEX `iduser_idx` (`userID` ASC),
  PRIMARY KEY (`userToRouteID`),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `overlandoo`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `routeID`
    FOREIGN KEY (`routeID`)
    REFERENCES `overlandoo`.`route` (`routeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
